# Generated by Django 3.1 on 2022-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220207_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
